In [1]:
import numpy as np

Generation of the other three variables basend on the value of the first variable.

In [2]:
# z = 0.03
# val = 1 - input_var** 2
# other_var_gen_1 = np.random.uniform(0, val)
# val2 = val - other_var_gen_1 ** 2
# other_var_gen_2 = np.sqrt(val - other_var_gen_1 ** 2)

# print(other_var_gen_2**2 + other_var_gen_1**2 + input_var**2)

Read txt file as a numpother_var_gen_1 arraother_var_gen_1

In [3]:
# Text file data converted to integer data type
File_data = np.loadtxt("t.txt", delimiter=';')
print(File_data)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [17]:
def gen_2_other_based_on_1(var_name='aX', var_value=0.):
    """_This function generates 2 parameters based on the input parameter value in a way that
        the following condition is fulfilled:

        aX^2 + aY^2 + aZ^2 = 1_

        Through the var_name parameter we specify the parameter on the basis of which the others will be generated.

    Args:
        var_name (str, optional): _name of the chosen variable_. Defaults to 'aX'.
        var_value (_float_, optional): _value of the chosen variable_. Defaults to 0..
    
    Returns:
        _numpy.ndarray_: one-dimensional vector of parameters [aX, aY, aZ]__
    """

    match var_name:
        case 'aX':
            input_var = var_value
            val = 1 - input_var** 2
            other_var_gen_1 = np.random.uniform(0, val)
            other_var_gen_2 = np.sqrt(val - other_var_gen_1 ** 2)
            
            return np.array([input_var, other_var_gen_1, other_var_gen_2])

        case 'aY':
            input_var = var_value
            val = 1 - input_var** 2
            other_var_gen_1 = np.random.uniform(0, val)
            other_var_gen_2 = np.sqrt(val - other_var_gen_1 ** 2)
            
            return np.array([other_var_gen_2, input_var, other_var_gen_1])

        case 'aZ':
            input_var = var_value
            val = 1 - input_var** 2
            other_var_gen_1 = np.random.uniform(0, val)
            other_var_gen_2 = np.sqrt(val - other_var_gen_1 ** 2)
            
            return np.array([other_var_gen_2, other_var_gen_1, input_var])
        
        case _:
            print("Wrong variable name!")

vec = gen_2_other_based_on_1(var_name='aX', var_value=0.3)
vec

array([0.3       , 0.77700103, 0.55341612])

In [15]:
print(vec[0]**2 + vec[1]**2 + vec[2]**2)

1.0


In [6]:
from AADecay12new import *

In [7]:
k = AADecay12new(1, 2, 3)
k.create_matrix()
k.A
k.gen_2_other_based_on_1(var_name='ay', var_value=0.01)

# AADecay12new.gen_2_other_based_on_1(var_name='aX', var_value=0.01)

array([0.9384578 , 0.01      , 0.34524912])