In [65]:
import numpy as np

In [66]:
class RotationMatrix:
    def __init__(self, theta=0, chi=0, phi=0):
        """_Class to create a rotation matrix in 4 dimensions based
        on the Euler angles (in radians) provided by the user._

        Args:
            theta (_float_): _the signed angle between the z axis and the Z axis_
            chi (_float_): _the signed angle between the N axis and the X axis_
            phi (_float_): _the signed angle between the x axis and the N axis_
        """
        self.theta = theta
        self.chi = chi
        self.phi = phi
        self.R = np.zeros((4, 4))
    
    def create(self):
        """_This function creates a rotation matrix based on the Euler angles_
        """
        theta = self.theta
        chi = self.chi
        phi = self.phi

        cth = np.cos(theta)
        sth = np.sin(theta)
        cch = np.cos(chi)
        sch = np.sin(chi)
        cph = np.cos(phi)
        sph = np.sin(phi)

        self.R[0, 0] = 1
        self.R[1, 1] = cth*cch*cph - sch*sph
        self.R[1, 2] = -cth*sch*cph - cch*sph
        self.R[1, 3] = sth*cph
        self.R[2, 1] = cth*cch*sph + sch*cph
        self.R[2, 2] = cch*cph - cth*sch*sph
        self.R[2, 3] = sth*sph
        self.R[3, 1] = -sth*cph
        self.R[3, 2] = sth*sch
        self.R[3, 3] = cth

Initialization of rotation matrix and example matrix

In [75]:
b = np.arange(0, 16).reshape(4, 4)

theta = np.radians(30)
phi = np.radians(45)
chi = np.radians(0)

RotMat = RotationMatrix(theta=theta, phi=phi, chi=chi)
RotMat.create()
R = RotMat.R
R

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.61237244, -0.70710678,  0.35355339],
       [ 0.        ,  0.61237244,  0.70710678,  0.35355339],
       [ 0.        , -0.35355339,  0.        ,  0.8660254 ]])

Calculation of rotation of b matrix (explicitly)

In [68]:
B = np.zeros((4, 4))

B[0, 0] = R[0, 0]*b[0, 0]
B[0, 1] = R[0, 0]*b[0, 1]
B[0, 2] = R[0, 0]*b[0, 2] 
B[0, 3] = R[0, 0]*b[0, 3]
B[1, 0] = R[1, 1]*b[1, 0] + R[1, 2]*b[2, 0] + R[1, 3]*b[3, 0]
B[1, 1] = R[1, 1]*b[1, 1] + R[1, 2]*b[2, 1] + R[1, 3]*b[3, 1]
B[1, 2] = R[1, 1]*b[1, 2] + R[1, 2]*b[2, 2] + R[1, 3]*b[3, 2]
B[1, 3] = R[1, 1]*b[1, 3] + R[1, 2]*b[2, 3] + R[1, 3]*b[3, 3]
B[2, 0] = R[2, 1]*b[1, 0] + R[2, 2]*b[2, 0] + R[2, 3]*b[3, 0]
B[2, 1] = R[2, 1]*b[1, 1] + R[2, 2]*b[2, 1] + R[2, 3]*b[3, 1]
B[2, 2] = R[2, 1]*b[1, 2] + R[2, 2]*b[2, 2] + R[2, 3]*b[3, 2]
B[2, 3] = R[2, 1]*b[1, 3] + R[2, 2]*b[2, 3] + R[2, 3]*b[3, 3]
B[3, 0] = R[3, 1]*b[1, 0] + R[3, 2]*b[2, 0] + R[3, 3]*b[3, 0]
B[3, 1] = R[3, 1]*b[1, 1] + R[3, 2]*b[2, 1] + R[3, 3]*b[3, 1]
B[3, 2] = R[3, 1]*b[1, 2] + R[3, 2]*b[2, 2] + R[3, 3]*b[3, 2]
B[3, 3] = R[3, 1]*b[1, 3] + R[3, 2]*b[2, 3] + R[3, 3]*b[3, 3]

B

array([[ 0.        ,  1.        ,  2.        ,  3.        ],
       [ 1.03527618,  1.29409523,  1.55291427,  1.81173332],
       [12.34898468, 14.02201729, 15.69504989, 17.3680825 ],
       [ 8.97809128,  9.4905633 , 10.00303531, 10.51550732]])

Using numpy function

In [69]:
B_prim = np.matmul(R, b)
B_prim

array([[ 0.        ,  1.        ,  2.        ,  3.        ],
       [ 1.03527618,  1.29409523,  1.55291427,  1.81173332],
       [12.34898468, 14.02201729, 15.69504989, 17.3680825 ],
       [ 8.97809128,  9.4905633 , 10.00303531, 10.51550732]])

Checking if changing one of the angles leads to a change in the whole rotation matrix

In [70]:
theta = np.radians(30)
phi = np.radians(45)
chi = np.radians(0)

RotMat = RotationMatrix(theta=theta, phi=phi, chi=chi)
RotMat.create()
R = RotMat.R
theta_prim = np.radians(90)
R

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.61237244, -0.70710678,  0.35355339],
       [ 0.        ,  0.61237244,  0.70710678,  0.35355339],
       [ 0.        , -0.35355339,  0.        ,  0.8660254 ]])

In [71]:
RotMat.theta = theta_prim
RotMat.create()
RotMat.R

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  4.32978028e-17, -7.07106781e-01,
         7.07106781e-01],
       [ 0.00000000e+00,  4.32978028e-17,  7.07106781e-01,
         7.07106781e-01],
       [ 0.00000000e+00, -7.07106781e-01,  0.00000000e+00,
         6.12323400e-17]])

Default behaviour

In [74]:
r = RotationMatrix()
r.create()
r.R

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1., -0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0., -0.,  0.,  1.]])